NXPLOG_EXTNS_LOGLEVEL=0x01
NXPLOG_NCIHAL_LOGLEVEL=0x01
NXPLOG_NCIX_LOGLEVEL=0x01
NXPLOG_NCIR_LOGLEVEL=0x01
NXPLOG_FWDNLD_LOGLEVEL=0x01
NXPLOG_TML_LOGLEVEL=0x01

NXP_NFC_DEV_NODE="/dev/nxp-nci"

MIFARE_READER_ENABLE=0x01

VZW_FEATURE_ENABLE=0x01

NXP_FW_NAME="libpn557_fw.so"

NXP_SYS_CLK_SRC_SEL=0x01

NXP_SYS_CLK_FREQ_SEL=0x02

NXP_SYS_CLOCK_TO_CFG=0x06

NXP_ACT_PROP_EXTN={2F, 02, 00}

NXP_EXT_TVDD_CFG=0x01

NXP_EXT_TVDD_CFG_1={20, 02, 0F, 01, A0, 0E, 0B, 31, 01, 01, 31, 00, 00, 00, 01, 00, D0, 0C}

NXP_EXT_TVDD_CFG_2={20, 02, 0F, 01, A0, 0E, 0B, 11, 01, C2, B2, 00, B2, 1E, 1F, 00, D0, 0C}
NXP_SET_CONFIG_ALWAYS=0x01

NXP_CORE_RF_FIELD={ 20, 02, 05, 01, A0, 62, 01, 00 }

NXP_I2C_FRAGMENTATION_ENABLED=0x00

NXP_SWP_FULL_PWR_ON=0x00

NXP_NFC_CHIP=0x09

NXP_CE_ROUTE_STRICT_DISABLE=0x01

NXP_DEFAULT_NFCEE_DISC_TIMEOUT=20

NXP_DEFAULT_NFCEE_TIMEOUT=20

NXP_SWP_RD_START_TIMEOUT=0x0A

NXP_SWP_RD_TAG_OP_TIMEOUT=0x01

DEFAULT_AID_ROUTE=0x00

DEFAULT_ISODEP_ROUTE=0x00

DEFAULT_OFFHOST_ROUTE=0x02

DEFAULT_TECH_ABF_ROUTE=0x01

DEFAULT_SYS_CODE_ROUTE=0x00

DEFAULT_AID_PWR_STATE=0x39

DEFAULT_ISODEP_PWR_STATE=0x3B

DEFAULT_OFFHOST_PWR_STATE=0x3B

DEFAULT_TECH_ABF_PWR_STATE=0x3B

DEFAULT_SYS_CODE_PWR_STATE=0x00

OFF_HOST_ESE_PIPE_ID=0x19
OFF_HOST_SIM_PIPE_ID=0x0A

NFA_POLL_BAIL_OUT_MODE=0x01

AID_MATCHING_PLATFORM=0x01

NXP_CHINA_TIANJIN_RF_ENABLED=0x01

NXP_SWP_SWITCH_TIMEOUT=0x0A

NXP_NFCC_STANDBY_TIMEOUT=20000

NXP_AGC_DEBUG_ENABLE=0x00

NXP_ENABLE_ADD_AID=0x01

NXP_CHECK_DEFAULT_PROTO_SE_ID=0x01

NXP_CN_TRANSIT_CMA_BYPASSMODE_ENABLE=0x00

NXP_CN_TRANSIT_BLK_NUM_CHECK_ENABLE=0x01

NXP_NCI_PARSER_LIBRARY=0x00

AID_BLOCK_ROUTE=0x00

NXP_HCEF_CMD_RSP_TIMEOUT_VALUE=5000


RF_STATUS_UPDATE_ENABLE=0x00

NFA_PROPRIETARY_CFG={05, FF, FF, 06, 81, 80, 70, FF, FF}

DEVICE_HOST_ALLOW_LIST={80:81}

OFFHOST_ROUTE_UICC={02}

PRESENCE_CHECK_ALGORITHM=2

ISO_DEP_MAX_TRANSCEIVE=0xFEFF
